telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

api:
  binance:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
  cbr:
    dailyRates: https://www.cbr-xml-daily.ru/daily_json.js

#db:
#  driver:
#    name: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/db
#  user: root
#  password: root

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


