telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

api:
  scheduler:
    rate: 120000
    notification: 600000
  binance:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
  cbr:
    dailyRates: https://www.cbr-xml-daily.ru/daily_json.js

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


